// Generated by IcedCoffeeScript 1.3.3e
var EventEmitter2, Socket, emitter;

Socket = require('sockjs-client');

EventEmitter2 = require('eventemitter2').EventEmitter2;

if (typeof SERVER !== "undefined" && SERVER !== null) {
  Socket = new WebSocket("ws://" + window.location.hostname + ":3000");
} else {
  Socket = new SockJS("http://" + window.location.hostname + ":3000/socket");
}

emitter = new EventEmitter2({
  wildcard: true,
  delimiter: '.',
  maxListeners: 20
});

emitter.onAny(function() {
  return Socket.send(JSON.stringify([this.event].concat(arguments)));
});

Socket.onopen(function() {
  return emitter.emit('socket.open');
});

Socket.onclose(function() {
  return emitter.emit('socket.close');
});

Socket.onmessage(function(e) {
  var args, command, _ref;
  _ref = JSON.parse(e.data), command = _ref[0], args = _ref[1];
  return emitter[command].apply(emitter, args);
});

module.exports = emitter;
